name: yolo
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - gitpython>=3.1.30
  - matplotlib>=3.3
  - numpy>=1.23.5
  - pillow>=10.3.0
  - psutil
  - pyyaml>=5.3.1
  - requests>=2.32.2
  - scipy>=1.4.1
  - tqdm>=4.66.3
  - pandas>=1.1.4
  - seaborn>=0.11.0
  - setuptools>=70.0.0
  - ipython
  - pip:
    - ultralytics>=8.2.34
    - opencv-python>=4.1.1
    - thop>=0.1.1
    - huggingface_hub
